### ISSUE TITLE
Server crashes because of java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by primitive0** [Oth3r/Sit#1]
I don't know, how to reproduce this error, but I think it should be pretty easy to fix.

**Stacktrace:**
```
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
        at one.oth3r.sit.Events.cleanUp(Events.java:236) ~[sit!-1.0.1+1.20-1.20.1.jar:?]
        at net.minecraft.class_1255.execute(class_1255.java:102) ~[server-intermediary.jar:?]
        at one.oth3r.sit.Events.lambda$register$0(Events.java:149) ~[sit!-1.0.1+1.20-1.20.1.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-5dc3b66c74aa05fa.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zig000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:2362) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Oth3r** [comment]
fixed in v1.0.2+1.20-1.20.1
